theme: jekyll-theme-cayman

title: Algorithmic Solutions for Grocery Delivery Applications
author: Jessina James

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

remote_theme: "pages-themes/cayman@v0.4.0"
